+++
# Accomplishments widget.
widget = "TA Courses"  # See https://sourcethemes.com/academic/docs/page-builder/
headless = true  # This file represents a page section.
active = true  # Activate this widget? true/false
weight = 50  # Order that this section will appear.

title = "TA Courses"
subtitle = ""

# Date format
#   Refer to https://sourcethemes.com/academic/docs/customization/#date-format
date_format = "Jan 2006"

# Accomplishments.
#   Add/remove as many `[[item]]` blocks below as you like.
#   `title`, `organization` and `date_start` are the required parameters.
#   Leave other parameters empty if not required.
#   Begin/end multi-line descriptions with 3 quotes `"""`.

[[item]]
  organization = "Northwestern University"
  title = "STAT 202 Introduction to Statistic"

  date_start = "Fall 17, Winter 18, Spring 18, Winter 19"
  date_end = ""
  description = "Data collection, summarization, correlation, regression, probability, sampling, estimation, tests of significance."

[[item]]
  organization = "Northwestern University"
  title = "STAT 325 Survey Sampling"

  date_start = "Fall 18"
  date_end = ""
  description = "Probability sampling, simple random sampling, error estimation, sample size, stratification, systematic sampling, replication methods, ratio and regression estimation, cluster sampling."


[[item]]
  organization = "Northwestern University"
  title = "STAT 302 Data Visualization"

  date_start = "Spring 19"
  date_end = ""
  description = "Introduction to the knowledge, skills, and tools required to visualize data of various formats across statistical domains and to create quality visualizations for both data exploration and presentation."

+++
